### ISSUE TITLE
Update version on crates.io

### ISSUE THREAD

**Issue by luckysori** [pduval/rustic_hal#1]
The latest version of this crate has yet to be published to crates.io. This means transitioning from 0.1.1 to 0.1.2.

**Comment by pduval** [comment]
Thanks a lot for the issue and pull request!
While the crates compiles and runs, It deserves a rewrite at some point as serde in particular has changed quite a lot since when I started.

**Comment by luckysori** [comment]
Thanks for the speedy merge! We intend to use the functionality provided by your crate so we could help with the rewrite :smile:
